// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3PVNP4iiQudIrCy_YykVXRzSTMZy-9Kw',
    appId: '1:378486152479:web:3f4af2b4d648502568642a',
    messagingSenderId: '378486152479',
    projectId: 'ridelink-demo',
    authDomain: 'ridelink-demo.firebaseapp.com',
    storageBucket: 'ridelink-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5doqo0RYBZBAJRV19GcxtYf-gekvf0Ww',
    appId: '1:378486152479:android:6778536e902f21c068642a',
    messagingSenderId: '378486152479',
    projectId: 'ridelink-demo',
    storageBucket: 'ridelink-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuh6zUYAjRfKiWhvVQJay1a0CXmCFql6c',
    appId: '1:378486152479:ios:0dd3d1bd15859ed968642a',
    messagingSenderId: '378486152479',
    projectId: 'ridelink-demo',
    storageBucket: 'ridelink-demo.appspot.com',
    iosBundleId: 'com.example.ridelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuh6zUYAjRfKiWhvVQJay1a0CXmCFql6c',
    appId: '1:378486152479:ios:0dd3d1bd15859ed968642a',
    messagingSenderId: '378486152479',
    projectId: 'ridelink-demo',
    storageBucket: 'ridelink-demo.appspot.com',
    iosBundleId: 'com.example.ridelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3PVNP4iiQudIrCy_YykVXRzSTMZy-9Kw',
    appId: '1:378486152479:web:91935a552535078268642a',
    messagingSenderId: '378486152479',
    projectId: 'ridelink-demo',
    authDomain: 'ridelink-demo.firebaseapp.com',
    storageBucket: 'ridelink-demo.appspot.com',
  );
}
